services:
  registry:
    image: registry:2
    hostname: registry
    ports:
      - 5000:5000
    labels:
      - dev.orbstack.domains=registry
    volumes:
      - registry_volume:/var/lib/registry

  proxy:
    image: s8d.local/nginx
    build: nginx
    hostname: proxy
    volumes:
      - ./certs:/shared-ssl
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/html/s8d:/usr/share/nginx/html/s8d
    environment:
      SHARED_DIR: /shared-ssl
    ports:
      - 80:80
      - 443:443
    labels:
      - dev.orbstack.domains=s8d.local,registry.s8d.local

  control-plane:
    image: rancher/k3s:v1.30.1-k3s1
    container_name: k3s-server
    hostname: k3s-server
    privileged: true
    ports:
      - 6443:6443 # API Server port
    volumes:
      - ./certs:/shared-ssl
      - ./k3s/registries.yaml:/etc/rancher/k3s/registries.yaml
    environment:
      K3S_TOKEN: 1234
    command: server

  worker-1:
    image: rancher/k3s:v1.30.1-k3s1
    container_name: worker-1
    hostname: worker-1
    privileged: true
    volumes:
      - ./certs:/shared-ssl
      - ./k3s/registries.yaml:/etc/rancher/k3s/registries.yaml
    environment:
      K3S_URL: https://k3s-server:6443
      K3S_TOKEN: 1234
    command: agent

volumes:
  registry_volume:
