apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-local
  name: nginx-local
spec:
  containers:
  - image: registry.s8d.local/nginx
    name: nginx-local
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
